title: あいすり〜む Volume.3
themes:
  - title: Opening
    commentators:
      - Notridfcchi
  - title: LEVEL3 100% トーク！
    commentators:
      - poronnotei
      - koeda11
      - dokuroflower
  - title: 2013年のPerfumeについて
    commentators:
      - bakushin2300
      - pittanko_pta
      - jaqwatdas
      - toshi110
      - santgva
      - kokubucamera
      - BoBpp
  - title: ドームツアーの予想！
    commentators:
      - hcaaabok
      - buchibuchi
      - nanno2009
  - title: Ending
    commentators:
      - Notridfcchi
  - title: 2部
    commentators:
      - Notridfcchi
      - BoBpp
opening_themes:
  - LEVEL3 100% トーク！
  - 2013年のPerfumeについて
  - ドームツアーの予想！
