title: あいすり〜む Volume.4
themes:
  - title: Opening
    commentators:
      - Notridfcchi
  - title: ぐるんぐるんツアーの感想を研究せよ
    commentators:
      - poronnotei
      - nanno2009
      - goziland
  - title: ぐるんぐるんツアーの感想を研究せよ
    commentators:
      - toshi110
      - goziland
      - koeda11
  - title: ぐるんぐるんツアーの感想を研究せよ
    commentators:
      - poronnotei
      - buchibuchi
      - koeda11
  - title: ぐるんぐるんツアーの感想を研究せよ
    commentators:
      - hanatyan
      - dreamer_silvet
      - hcaaabok
  - title: ぐるんぐるんツアーの感想を研究せよ
    commentators:
      - nanno2009
      - toshi110
      - hcaaabok
      - dabu_cchi
  - title: Ending
    commentators:
      - Notridfcchi
  - title: 2部
    commentators:
      - Notridfcchi
opening_themes:
  - ぐるんぐるんツアーの感想を研究せよ

